### PR TITLE
changed: removed ' in path for working on Windows system

### PR DESCRIPTION
**Pull request by accountuse**
webp8 on Windows

preparing:

- install PHP, [Composter](https://getcomposer.org/Composer-Setup.exe) and [cwebp](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.0-windows-x64.zip)
- add pathes for Composter, PHP and cwebp in Environment Variables (sysdm.cpl -> Advanced -> E.V.)
- restart system
- composter install

run:

php src/webp8.php convert [Directory]

### CODE REVIEW

**Comment by 8ctopus** [comment]
thank you for the pull request, how will the changes affect linux systems?

**Comment by accountuse** [comment]
> thank you for the pull request, how will the changes affect linux systems?

It seems that nothing has changed) convert and cleanup work, but maybe I did not notice something.

**Comment by 8ctopus** [comment]
> webp8 on Windows
> 
> preparing:
> 
> * install PHP, [Composter](https://getcomposer.org/Composer-Setup.exe) and [cwebp](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.0-windows-x64.zip)
> * add pathes for Composter, PHP and cwebp in Environment Variables (sysdm.cpl -> Advanced -> E.V.)
> * restart system
> * composter install
> 
> run:
> 
> php src/webp8.php convert [Directory]

please add to README

**Comment by 8ctopus** [comment]
> > thank you for the pull request, how will the changes affect linux systems?
> 
> It seems that nothing has changed) convert and cleanup work, but maybe I did not notice something.

I pretty sure I put the '' for a reason, can you update your code to something like that?

```php
if ($windows)
    $command = "cwebp {$options} {$src} -o {$dest}";
else
    $command = "cwebp {$options} '{$src}' -o '{$dest}'";
```

**Review by 8ctopus — APPROVED** [review]

**Comment by 8ctopus** [comment]
only README update missing

**Comment by 8ctopus** [comment]
[https://www.php.net/manual/en/function.php-uname.php](https://www.php.net/manual/en/function.php-uname.php) php_uname('s') seems to be a better choice to check the OS the script is running on.

**Review by 8ctopus — APPROVED** [review]
All good thank you!

**Pull request merged**
